### ISSUE TITLE
block comments

### ISSUE THREAD

**Issue by DontBeAlarmed** [HYP3R00T/settings-organizer#3]
I'd use block comments to mark areas like this until they're sorted out
// vim_start
  "vim.sneak": true,
  ......
  "vim.useSystemClipboard": true,
// vim_end
Now my settings look like this
  "vim.sneak": true, // vim_start
  ......
  "vim.useSystemClipboard": true, // vim_end
I think this is fine too

**Comment by HYP3R00T** [comment]
We have a new issue with a similar concern. Please follow #4 . I am closing this issue.
